# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vince/Downloads/GolfAtHome

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vince/Downloads/GolfAtHome

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vince/Downloads/GolfAtHome/CMakeFiles /home/vince/Downloads/GolfAtHome//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vince/Downloads/GolfAtHome/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GolfAtHome

# Build rule for target.
GolfAtHome: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GolfAtHome
.PHONY : GolfAtHome

# fast build rule for target.
GolfAtHome/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GolfAtHome.dir/build.make CMakeFiles/GolfAtHome.dir/build
.PHONY : GolfAtHome/fast

src/generators/AbstractPrecomputeGenerator.o: src/generators/AbstractPrecomputeGenerator.cpp.o
.PHONY : src/generators/AbstractPrecomputeGenerator.o

# target to build an object file
src/generators/AbstractPrecomputeGenerator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GolfAtHome.dir/build.make CMakeFiles/GolfAtHome.dir/src/generators/AbstractPrecomputeGenerator.cpp.o
.PHONY : src/generators/AbstractPrecomputeGenerator.cpp.o

src/generators/AbstractPrecomputeGenerator.i: src/generators/AbstractPrecomputeGenerator.cpp.i
.PHONY : src/generators/AbstractPrecomputeGenerator.i

# target to preprocess a source file
src/generators/AbstractPrecomputeGenerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GolfAtHome.dir/build.make CMakeFiles/GolfAtHome.dir/src/generators/AbstractPrecomputeGenerator.cpp.i
.PHONY : src/generators/AbstractPrecomputeGenerator.cpp.i

src/generators/AbstractPrecomputeGenerator.s: src/generators/AbstractPrecomputeGenerator.cpp.s
.PHONY : src/generators/AbstractPrecomputeGenerator.s

# target to generate assembly for a file
src/generators/AbstractPrecomputeGenerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GolfAtHome.dir/build.make CMakeFiles/GolfAtHome.dir/src/generators/AbstractPrecomputeGenerator.cpp.s
.PHONY : src/generators/AbstractPrecomputeGenerator.cpp.s

src/generators/main.o: src/generators/main.cpp.o
.PHONY : src/generators/main.o

# target to build an object file
src/generators/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GolfAtHome.dir/build.make CMakeFiles/GolfAtHome.dir/src/generators/main.cpp.o
.PHONY : src/generators/main.cpp.o

src/generators/main.i: src/generators/main.cpp.i
.PHONY : src/generators/main.i

# target to preprocess a source file
src/generators/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GolfAtHome.dir/build.make CMakeFiles/GolfAtHome.dir/src/generators/main.cpp.i
.PHONY : src/generators/main.cpp.i

src/generators/main.s: src/generators/main.cpp.s
.PHONY : src/generators/main.s

# target to generate assembly for a file
src/generators/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GolfAtHome.dir/build.make CMakeFiles/GolfAtHome.dir/src/generators/main.cpp.s
.PHONY : src/generators/main.cpp.s

src/lib/RP/RPGolConfig.o: src/lib/RP/RPGolConfig.cpp.o
.PHONY : src/lib/RP/RPGolConfig.o

# target to build an object file
src/lib/RP/RPGolConfig.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GolfAtHome.dir/build.make CMakeFiles/GolfAtHome.dir/src/lib/RP/RPGolConfig.cpp.o
.PHONY : src/lib/RP/RPGolConfig.cpp.o

src/lib/RP/RPGolConfig.i: src/lib/RP/RPGolConfig.cpp.i
.PHONY : src/lib/RP/RPGolConfig.i

# target to preprocess a source file
src/lib/RP/RPGolConfig.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GolfAtHome.dir/build.make CMakeFiles/GolfAtHome.dir/src/lib/RP/RPGolConfig.cpp.i
.PHONY : src/lib/RP/RPGolConfig.cpp.i

src/lib/RP/RPGolConfig.s: src/lib/RP/RPGolConfig.cpp.s
.PHONY : src/lib/RP/RPGolConfig.s

# target to generate assembly for a file
src/lib/RP/RPGolConfig.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GolfAtHome.dir/build.make CMakeFiles/GolfAtHome.dir/src/lib/RP/RPGolConfig.cpp.s
.PHONY : src/lib/RP/RPGolConfig.cpp.s

src/lib/RP/RPGolWindSet.o: src/lib/RP/RPGolWindSet.cpp.o
.PHONY : src/lib/RP/RPGolWindSet.o

# target to build an object file
src/lib/RP/RPGolWindSet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GolfAtHome.dir/build.make CMakeFiles/GolfAtHome.dir/src/lib/RP/RPGolWindSet.cpp.o
.PHONY : src/lib/RP/RPGolWindSet.cpp.o

src/lib/RP/RPGolWindSet.i: src/lib/RP/RPGolWindSet.cpp.i
.PHONY : src/lib/RP/RPGolWindSet.i

# target to preprocess a source file
src/lib/RP/RPGolWindSet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GolfAtHome.dir/build.make CMakeFiles/GolfAtHome.dir/src/lib/RP/RPGolWindSet.cpp.i
.PHONY : src/lib/RP/RPGolWindSet.cpp.i

src/lib/RP/RPGolWindSet.s: src/lib/RP/RPGolWindSet.cpp.s
.PHONY : src/lib/RP/RPGolWindSet.s

# target to generate assembly for a file
src/lib/RP/RPGolWindSet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GolfAtHome.dir/build.make CMakeFiles/GolfAtHome.dir/src/lib/RP/RPGolWindSet.cpp.s
.PHONY : src/lib/RP/RPGolWindSet.cpp.s

src/lib/RP/RPUtlRandom.o: src/lib/RP/RPUtlRandom.cpp.o
.PHONY : src/lib/RP/RPUtlRandom.o

# target to build an object file
src/lib/RP/RPUtlRandom.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GolfAtHome.dir/build.make CMakeFiles/GolfAtHome.dir/src/lib/RP/RPUtlRandom.cpp.o
.PHONY : src/lib/RP/RPUtlRandom.cpp.o

src/lib/RP/RPUtlRandom.i: src/lib/RP/RPUtlRandom.cpp.i
.PHONY : src/lib/RP/RPUtlRandom.i

# target to preprocess a source file
src/lib/RP/RPUtlRandom.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GolfAtHome.dir/build.make CMakeFiles/GolfAtHome.dir/src/lib/RP/RPUtlRandom.cpp.i
.PHONY : src/lib/RP/RPUtlRandom.cpp.i

src/lib/RP/RPUtlRandom.s: src/lib/RP/RPUtlRandom.cpp.s
.PHONY : src/lib/RP/RPUtlRandom.s

# target to generate assembly for a file
src/lib/RP/RPUtlRandom.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GolfAtHome.dir/build.make CMakeFiles/GolfAtHome.dir/src/lib/RP/RPUtlRandom.cpp.s
.PHONY : src/lib/RP/RPUtlRandom.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GolfAtHome"
	@echo "... src/generators/AbstractPrecomputeGenerator.o"
	@echo "... src/generators/AbstractPrecomputeGenerator.i"
	@echo "... src/generators/AbstractPrecomputeGenerator.s"
	@echo "... src/generators/main.o"
	@echo "... src/generators/main.i"
	@echo "... src/generators/main.s"
	@echo "... src/lib/RP/RPGolConfig.o"
	@echo "... src/lib/RP/RPGolConfig.i"
	@echo "... src/lib/RP/RPGolConfig.s"
	@echo "... src/lib/RP/RPGolWindSet.o"
	@echo "... src/lib/RP/RPGolWindSet.i"
	@echo "... src/lib/RP/RPGolWindSet.s"
	@echo "... src/lib/RP/RPUtlRandom.o"
	@echo "... src/lib/RP/RPUtlRandom.i"
	@echo "... src/lib/RP/RPUtlRandom.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

